### PR TITLE
Fix a bug where the jinja template for `analyticsories_detection` cra…

### LINKED ISSUE #313: Error: jinja2.exceptions.UndefinedError: 'str object' has no attribute 'value'
When upgrading contentctl to 4.4.0 from 4.2.2, I got some new errors without changing my contentctl package. One of them is:

```
Verbose error logging is ENABLED.
The entire stack trace has been provided below (please include it if filing a bug report):

Traceback (most recent call last):
  File "\\wsl.localhost\Ubuntu\home\<user>\sigmastuff\contentctl\contentctl\contentctl.py", line 211, in main
    test_common_func(config)
  File "\\wsl.localhost\Ubuntu\home\<user>\sigmastuff\contentctl\contentctl\contentctl.py", line 107, in test_common_func
    director_output_dto = build_func(config)
                          ^^^^^^^^^^^^^^^^^^
  File "\\wsl.localhost\Ubuntu\home\<user>\sigmastuff\contentctl\contentctl\contentctl.py", line 80, in build_func
    return builder.execute(BuildInputDto(director_output_dto, config))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\wsl.localhost\Ubuntu\home\<user>\sigmastuff\contentctl\contentctl\actions\build.py", line 47, in execute
    updated_conf_files.update(conf_output.writeObjects(input_dto.director_output_dto.detections, SecurityContentType.detections))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\wsl.localhost\Ubuntu\home\<user>\sigmastuff\contentctl\contentctl\output\conf_output.py", line 81, in writeObjects
    written_files.add(ConfWriter.writeConfFile(pathlib.Path(output_app_path),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "\\wsl.localhost\Ubuntu\home\<user>\sigmastuff\contentctl\contentctl\output\conf_writer.py", line 163, in writeConfFile
    output = template.render(objects=objects, app=config.app)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\<user>\.virtualenvs\sigmastuff-YzDXeAfS\Lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\<user>\.virtualenvs\sigmastuff-YzDXeAfS\Lib\site-packages\jinja2\environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "\\wsl.localhost\Ubuntu\home\<user>\sigmastuff\contentctl\contentctl\output\templates\analyticstories_detections.j2", line 8, in top-level template code
    asset_type = {{ detection.tags.asset_type.value }}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'str object' has no attribute 'value'

```

When running `contentctl test --enable-integration-testing --verbose mode:all`

Here is my `Detection` YAML:

```yaml
author: Someone
data_sources: []
date: '2024-10-21'
description: "something"
drilldown_searches:
- earliest_offset: $info_min_time$
  latest_offset: $info_max_time$
  name: DummyDrilldown1
  search: '%original_detection_search%'
- earliest_offset: $info_min_time$
  latest_offset: $info_max_time$
  name: DummyDrilldown2
  search: '%original_detection_search%'
how_to_implement: Nothing
id: 8e7eeb73-69f4-48cf-b1f4-19c4872f68eb
known_false_positives: Nonee
name: Some detection
references: []
search: 'something=something

  | `some_detection`'
status: production
tags:
  analytic_story: []
  asset_type: Account
  confidence: 1
  cve: []
  impact: 60
  message: N/A
  mitre_attack_id:
  - T1555
  observable:
  - name: ' '
    role:
    - Victim
    type: Unknown
  product:
  - Splunk Enterprise Security
  required_fields:
  - nothing
  risk_score: N/A
  security_domain: access
tests:
- attack_data:
  - data: ./tests/some_detection/shouldtrigger_1.test
    source: N/A
    sourcetype: N/A
  name: shouldtrigger_1
  test_type: unit
type: TTP
version: 1
```

When debugging, `detection.tags.asset_type` has the value `Account` and is a `str` object, which does not have a `.value`.

### PR DESCRIPTION
**Pull request by Res260**
Fix a bug where the jinja template for `analyticsories_detection` crashed when specifying a `detection.tags.asset_type`. Fixes #313.

### CODE REVIEW

**Comment by pyth0n1c** [comment]
Hi @Res260 - I am having trouble replicating this bug, even using the example Detection you provided.  
When I poke around at the value of `detection.tags.asset_type`, it is showing me it is `enum 'AssetType'`
This is with the latest version of contentctl in `main`
Did you make any other changes in your fork, potential around the `use_enum_values` configDict Pydantic setting?

image

**Comment by Res260** [comment]
I have not. I'm using Python 3.12, are you using the same version?

**Comment by Res260** [comment]
Specifically, I'm running Python `3.12.6` on Windows 11.

Here is a snippet of my `pip freeze`:

```
annotated-types==0.7.0
antlr4-python3-runtime==4.9.3
arrow==1.3.0
artifacts-keyring==0.3.6
attackcti==0.4.4
attrs==24.2.0
azure-common==1.1.28
azure-core==1.31.0
azure-identity==1.14.0
azure-mgmt-core==1.4.0
azure-mgmt-securityinsight==1.0.0
beautifulsoup4==4.12.2
bottle==0.12.25
certifi==2024.8.30
cffi==1.17.1
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
colour==0.1.5
contentctl==20241107.21.54
cpe==1.3.0
cryptography==43.0.1
cybox==2.1.0.21
deepdiff==8.0.1
deprecation==2.1.0
distlib==0.3.8
docker==7.1.0
docstring_parser==0.16
drawsvg==2.4.0
et-xmlfile==1.1.0
fancycompleter==0.9.1
filelock==3.16.1
fqdn==1.5.1
gitdb==4.0.11
GitPython==3.1.43
idna==3.10
iniconfig==2.0.0
isodate==0.6.1
isoduration==20.11.0
jaraco.classes==3.4.0
jaraco.context==6.0.1
jaraco.functools==4.0.2
Jinja2==3.1.4
jsonpointer==3.0.0
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
keyring==25.4.1
loguru==0.7.2
lxml==5.3.0
maec==4.1.0.17
Markdown==3.7
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mdurl==0.1.2
mitreattack-python==3.0.6
mixbox==1.0.5
more-itertools==10.5.0
msal==1.31.0
msal-extensions==1.2.0
msrest==0.7.1
netaddr==1.3.0
numpy==2.1.1
oauthlib==3.2.2
openpyxl==3.1.5
ordered-set==4.1.0
orderly-set==5.2.2
packaging==24.1
pandas==2.2.3
pdbpp==0.10.3
pillow==10.4.0
pipenv==2024.0.3
platformdirs==4.3.6
pluggy==1.5.0
pluralizer==1.2.0
pooch==1.8.2
portalocker==2.10.1
prettytable==3.10.0
prompt-toolkit==3.0.36
pycountry==24.6.1
pycparser==2.22
pycvesearch==1.2
pydantic==2.9.2
pydantic_core==2.23.4
pygit2==1.15.1
Pygments==2.18.0
PyJWT==2.9.0
pyparsing==3.1.4
pyreadline3==3.5.4
pyrepl==0.9.0
pySigma==0.11.17
pytest==8.3.3
python-certifi-win32==1.6.1
python-dateutil==2.9.0.post0
pytz==2024.2
pywin32==306
pywin32-ctypes==0.2.3
PyYAML==6.0.2
questionary==2.0.1
referencing==0.35.1
requests==2.32.3
requests-oauthlib==2.0.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.8.1
rpds-py==0.20.0
semantic-version==2.10.0
setuptools==70.3.0
setuptools-scm==8.1.0
shellingham==1.5.4
shtab==1.7.1
sigma-cli==1.0.4
simplejson==3.19.3
six==1.16.0
smmap==5.0.1
soupsieve==2.6
splunk-sdk==2.0.2
stix==1.2.0.11
stix2==3.0.1
stix2-elevator==4.1.7
stix2-patterns==2.0.0
stix2-validator==3.2.0
stixmarx==1.0.8
tabulate==0.9.0
taxii2-client==2.3.0
tqdm==4.66.5
typer==0.12.5
types-python-dateutil==2.9.0.20240906
typing_extensions==4.12.2
tyro==0.8.11
tzdata==2024.2
uri-template==1.3.0
urllib3==2.2.3
virtualenv==20.26.5
wcwidth==0.2.13
weakrefmethod==1.0.3
webcolors==24.8.0
win32-setctime==1.1.0
wmctrl==0.5
wrapt==1.16.0
XlsxWriter==3.2.0
xmltodict==0.13.0
```

**Comment by pyth0n1c** [comment]
Thanks for the more specific debug info @Res260  - I will try to replicate this exact config and try to debug more locally 😄 

We also have an issue to remove the widespread use of `use_enum_values` which leads to lots of.... weird requirements to use the enum or enum.value in different types of comparisons/serializations:
https://github.com/splunk/contentctl/issues/266

**Comment by pyth0n1c** [comment]
All the enums in our codebase have been updated to either `StrEnum` or `IntEnum` which has allowed us to remove the weird, seemingly pseudo-random usages of `enumName.value` all over the codebase.  This was done in the following PR: https://github.com/splunk/contentctl/pull/335 which has been merged into our next big update, the contentctl_5 PR: https://github.com/splunk/contentctl/pull/334 

I believe that this will fix the issue at it's source, but I will need to do some testing to ensure that is the case.

**Comment by pyth0n1c** [comment]
Closing this as, as moving enums to StrEnum and IntEnum seems to have resolved the underlying issue.
